# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '그림판.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 400)
        self.lb_canvas = QtWidgets.QLabel(Form)
        self.lb_canvas.setGeometry(QtCore.QRect(10, 10, 481, 301))
        self.lb_canvas.setObjectName("lb_canvas")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 320, 481, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_black = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_black.setText("")
        self.btn_black.setObjectName("btn_black")
        self.horizontalLayout.addWidget(self.btn_black)
        self.btn_red = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_red.setText("")
        self.btn_red.setObjectName("btn_red")
        self.horizontalLayout.addWidget(self.btn_red)
        self.btn_blue = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_blue.setText("")
        self.btn_blue.setObjectName("btn_blue")
        self.horizontalLayout.addWidget(self.btn_blue)
        self.btn_clear = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_clear.setObjectName("btn_clear")
        self.horizontalLayout.addWidget(self.btn_clear)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lb_canvas.setText(_translate("Form", "TextLabel"))
        self.btn_clear.setText(_translate("Form", "모두지움"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
